### ISSUE TITLE
When using --all-layers, unpublished layers are included

### ISSUE THREAD

**Issue by kscherer** [Wind-River/wr-lx-setup#5]
The layerindex-web api endpoint for layers includes published and unpublished layers. If an unpublished layer contains an invalid git url then the setup program can fail. This is a good way to test if the submitted layer is valid, so I think the setup program should ignore unpublished layers by default, but still provide a way to use them to help with testing.

**Comment by mhatle** [comment]
I've discussed the issue w/ Paul Eggleton (maintainer of the layer index).  He indicated this is a bug in the layerindex, unpublished layers should not show up via the rest API.

He indicated that he has a fix for the issue and it should go into production today.
